# Generated by Django 2.1.8 on 2019-11-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Client Name')),
                ('street_name', models.CharField(max_length=255, verbose_name='Street Name')),
                ('suburb', models.CharField(max_length=255, verbose_name='Suburb')),
                ('postcode', models.CharField(max_length=255, verbose_name='Postcode')),
                ('state', models.CharField(max_length=16, verbose_name='State')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Contact Name')),
                ('email_address', models.EmailField(max_length=255, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Phone Number')),
            ],
        ),
    ]
