# Generated by Django 2.1.8 on 2019-11-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postcode',
            field=models.CharField(blank=True, max_length=255, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=16, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='suburb',
            field=models.CharField(blank=True, max_length=255, verbose_name='Suburb'),
        ),
    ]
